### ISSUE TITLE
Potential command injection vulnerability

### ISSUE THREAD

**Issue by xiaofen9** [zacanger/is-program-installed#6]
# Is this a feature request or a bug?
bug

# Actual behavior:

The bug is introduced because the package-exported method `isInstalled()` fails to sanitize the parameter and let it flow into a sensitive command execution API.

Here is the proof of concept.
```
const isInstalled = require("is-program-installed")
isInstalled('&touch rce&')// a file named rce will be created
```
Please consider fix it. thanks!

**Comment by zacanger** [comment]
Thank you for the report. Patched in 6d16c95b6b57b0bcb5614b68b05bfda0bc338783 and published in v2.3.8. Unfortunately it's difficult to completely sanitize a potential file or command name because users will sometimes do silly things like including an ampersand in the middle of a filename, but this extra replace is an improvement.
